services:
  nginx:
    build:
      context: requirements/nginx
      dockerfile: Dockerfile
      args:
        CERT_PATH: ${CERT_PATH}
        KEY_PATH: ${KEY_PATH}
        DOMAIN_NAME: ${DOMAIN_NAME}
    container_name: nginx
    depends_on:
      - wordpress
    ports:
      - "443:443"
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - inception_network
    restart: unless-stopped
    env_file:
      - ~/.local/.env
    image: nginx
    healthcheck:
      test: ["CMD", "curl", "-k", "-f", "https://localhost:443"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  wordpress:
    build:
      context: requirements/wordpress
      dockerfile: Dockerfile
    container_name: wordpress
    depends_on:
      - mariadb
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - inception_network
    restart: unless-stopped
    env_file:
      - ~/.local/.env
    image: wordpress
    healthcheck:
      test: ["CMD", "pidof", "php-fpm7.4"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  mariadb:
    build:
      context: requirements/mariadb
      dockerfile: Dockerfile
    container_name: mariadb
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - inception_network
    restart: unless-stopped
    env_file:
      - ~/.local/.env
    image: mariadb
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

volumes:
  wordpress_data:
    driver: local
    driver_opts:
      type: none
      device: /home/${USER}/data/wordpress
      o: bind
  db_data:
    driver: local
    driver_opts:
      type: none
      device: /home/${USER}/data/mariadb
      o: bind

networks:
  inception_network:
    driver: bridge
